### ISSUE TITLE
Extra "</start_of_turn>" was shown on the end when talking with gemma2.

### ISSUE THREAD

**Issue by owenzhao** [kghandour/Ollama-SwiftUI#44] opened 2024-07-10 05:28 UTC
Ollama 0.2.1
Ollama Swift 2.0 (1).

**Comment by kghandour** [comment] 2024-07-16 15:47
Thanks for reporting this issue. It looks like there is an issue with running Gemma2 locally for me. I will look into it.

**Comment by kghandour** [comment] 2024-08-04 08:59
Tested in next update and looks like it is working.
After testing out Ollama Swift 2.0.1 let me know if it gets fixed.

![image](https://github.com/user-attachments/assets/cf0a3b78-c2ca-499d-a131-8b0ffffe72b1)

**Comment by kghandour** [comment] 2024-08-04 09:23
Closing this issue for now. If you test 2.0.1 and the issue is still there, please reopen.

**Closed by kghandour** 2024-08-04 09:23 UTC
